### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by dev-chriss** [hasib32/rest-api-with-lumen#11]
update app\Providers\RepositoriesServiceProvider.php :

use App\Repositories\Contracts\MessageRepository;
use App\Repositories\EloquentMessageRepository;

**Comment by hasib32** [comment]
@chrissetyawan Thanks for creating the issue. I can update the readme of  If you want you can create a Pull Request.

**Comment by dev-chriss** [comment]
u re welcome.
i already create a pull request.

 thnx.

**Comment by hasib32** [comment]
Updated readme https://github.com/hasib32/rest-api-with-lumen/commit/1673cdd1eb8214c7e64a486d266f38a88c94fb15.
