### ISSUE TITLE
Problem with Mocking Repository Model

### ISSUE THREAD

**Issue by ibpavlov** [hasib32/rest-api-with-lumen#22]
I have a problem mocking the Model of a Repository. Now the class is directly used in your code and the only way to Mock it is to overwrite it using Reflection, which is not the best practice. 

  ```
protected $modelName = User::class;
```

Isn't it better to use the assignment in the construction like: 

```
public function __construct(Model $model)
{
    $this->model = $model;
    $this->loggedInUser = $this->getLoggedInUser();
}
```

Please tell me what you think about this approach.

**Comment by shahriar1** [comment]
@ibpavlov I think you're right about it - here it'd be better to use the constructor to initialize the model.

@hasib32 you should update the `AbstractEloquentRepository` class to reflect this change

**Comment by hasib32** [comment]
@ibpavlov Thanks for the recommendation. If you want you can create a pull request for the change.
