### ISSUE TITLE
No getting information

### ISSUE THREAD

**Issue by limaho** [hasib32/rest-api-with-lumen#32]
After getting the accessToken without any problem, how can I get another information from API. For example I trying to get the information of current user doing this: 

![screenshot from 2017-07-29 11-41-49](https://user-images.githubusercontent.com/30474639/28746505-47c78970-7453-11e7-8b99-93fd69562c49.png)
![screenshot from 2017-07-29 11-43-02](https://user-images.githubusercontent.com/30474639/28746506-4a3a7ea6-7453-11e7-8d83-ee34048ae050.png)

But I am getting this when I use http://localhost/users/me: 

`{
    "status": 405,
    "message": "Method Not Allowed"
}`

http://localhost/users

`{
    "status": 401,
    "message": "Unauthorized"
}
`
Also If I want to save new user or update. If someone has done this, can you share it. Thank you

**Comment by hasib32** [comment]
Hi, you are using method type `POST` you should use `GET`

**Comment by kabelo38** [comment]
LOL we can't access your localhost

For furthur API request after getting your access_token and refresh token, on your Header you have to add additional header "Authorization" and put access_token as the value

Understanding grant password : http://docs.apigee.com/api-services/content/implementing-password-grant-type
![more_calls_api_hasib32](https://user-images.githubusercontent.com/5912376/28893309-3a320dc2-77d1-11e7-840f-f964dd96230b.png)

**Comment by hasib32** [comment]
Thanks @kabelo38

**Comment by limaho** [comment]
@hasib32 Thanks, was my mistake

**Comment by hasib32** [comment]
@limaho No problem. I'm going to close the issue.
