### ISSUE TITLE
rest route patch

### ISSUE THREAD

**Issue by Breadem** [hasib32/rest-api-with-lumen#34]
I didn't see "patch" method in route , only have "put" to update  resources.
Should I add patch to update resources in partly?

**Comment by hasib32** [comment]
Sure. If you want you can create a pull request.

**Comment by Breadem** [comment]
Thanks.  
I am a programming novice,If I can write the codes in right way,I will create a pull request.
I learn a lot knowledge in your blog. Thank you very much.
