### ISSUE TITLE
Autoload file not generate

### ISSUE THREAD

**Issue by anishbhut** [hasib32/rest-api-with-lumen#37]
Hi 

I have clone repository and write command composer update, 5 folder added in vendor folder but autoload file not generated

Warning: require_once(D:\xampp\htdocs\rest-api-with-lumen\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\rest-api-with-lumen\bootstrap\app.php on line 3

Fatal error: require_once(): Failed opening required 'D:\xampp\htdocs\rest-api-with-lumen\bootstrap/../vendor/autoload.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\rest-api-with-lumen\bootstrap\app.php on line 3

please help

**Comment by shahriar1** [comment]
Follow the setup instructions and try running `composer install` instead of `composer update`
