### ISSUE TITLE
Getting 404 on every request

### ISSUE THREAD

**Issue by pattle** [hasib32/rest-api-with-lumen#38]
First of all thanks for putting this boilerplate together.  

I've gone through the setup guide but I keep getting 404's on every request.  I'm not running the project using homestead, instead I want to be able to just go to http://localhost/project-name/public but this returns a 404.  

Am I missing a step?  Any help is greatly appreciated.

**Comment by hasib32** [comment]
Hi, `public` is not a valid api endpoint/resource. only valid endpoint is `users`

**Comment by pattle** [comment]
Thanks for the quick response.  If I remove the `public` I just get a directory listing as the `index.php` is in the public folder

**Comment by hasib32** [comment]
try http://localhost/project-name/users. and how are you running the application?

**Comment by pattle** [comment]
That gives me the apache not found page rather than a JSON response.  I'm just running the project using WAMP on Windows.  In your tutorial your base url is `http://restapi.app` but because I'm not using vagrant and homestead mine should just be `http://localhost/project-name/public`.  

Do you think it could be a .htaccess problem?

**Comment by hasib32** [comment]
Try running `php artisan serve` it should give you an url.

**Comment by pattle** [comment]
I think the `serve` command has been removed but if I run `php -S localhost:8080 -t public/` the application now works.  

Do you know why this now works?  I'm worried that if I deploy to production I'm going to have the same problem but no understanding of why it's happening.

**Comment by hasib32** [comment]
Before you did not have any server. Now, you are running the application with built in php server.
