### ISSUE TITLE
Upgrade to lumen 5.5

### ISSUE THREAD

**Issue by vbezruchkin** [hasib32/rest-api-with-lumen#40]
Hi,

The project looks interesting. I'm going to use it for one project, but I'm not sure if I need to use the previous version. Do you have any plans to upgrade it to 5.5? Should I wait or can start using current version.

Thanks in advance.

**Comment by hasib32** [comment]
Hi @vbezruchkin thanks for your interest. I'm planning to upgrade the project to 5.5 this weekend. You are also welcome to submit a pull request.

**Comment by vbezruchkin** [comment]
Thanks :) I will be waiting for it then!

Good luck!

**Comment by daim2k5** [comment]
@hasib32 can you get us a status? Or which problems we can solve with you?

**Comment by vbezruchkin** [comment]
Hi, not sure what status you expect, guys :) I was going to check the solution using Laravel 5.5, I have not checked the current version. I'm not in rush so I can easily wait the new version you wanted to prepare.

Thanks

**Comment by hasib32** [comment]
Hi, I'm very sorry. I could not update the Version to 5.5. I promise I will do by this week.

**Comment by vbezruchkin** [comment]
No rush at all. I can easily wait! Thanks for your efforts! I do understand we can busy sometimes!

I'd really like to give it a try, as it looks as something I might need to start a new project.

Thanks in advance!

**Comment by nirmalgoswami** [comment]
any updates related v5.5 ?

**Comment by ibpavlov** [comment]
Last month I've done it for a clone, so I will try to update it in a week and publish a Pull Reuqest.

**Comment by nirmalgoswami** [comment]
Thanks, Appreciated

**Comment by cdave3** [comment]
Also awaiting 5.5 release, thanks. :+1:

**Comment by ibpavlov** [comment]
Done. It will be time to update to 5.6 soon :)
