### ISSUE TITLE
Target [Illuminate\Contracts\Http\Kernel] is not instantiable.

### ISSUE THREAD

**Issue by ShayanSolution** [hasib32/rest-api-with-lumen#52]
After cloning repo. when i try to run 

php artisan migrate

i am getting following error

  [Illuminate\Contracts\Container\BindingResolutionException]
  Target [Illuminate\Contracts\Http\Kernel] is not instantiable.

php : 7.0.23

**Comment by hasib32** [comment]
Did you run `composer install`

**Comment by ShayanSolution** [comment]
I noticed that some old composer.lock file was causing issue. I removed composer.lock file and then re-installed. 

It works now. 

Thank you
