### ISSUE TITLE
Refresh Token Problem

### ISSUE THREAD

**Issue by kemalatila** [hasib32/rest-api-with-lumen#55]
How can I refresh my token with only sending refresh token? Is there anything for that?

**Comment by isogram** [comment]
Hi @kemalatila , you can use `your-url.com/oauth/token` with post method and form data like this to refresh token:
```
grant_type:refresh_token
refresh_token:{{refresh_token}}
client_id:{{client_id}}
client_secret:{{client_secret}}
access_token:{{access_token}}
```

you can see the code here `\Laravel\Passport\Http\Controllers\AuthorizedAccessTokenController`
